### ISSUE TITLE
Update JFOAAS to 1.0.0 equivalent of FOAAS.

### ISSUE THREAD

**Issue by SSederberg** [AnUnknownMiner/FOAAS-Java#3]
FOAAS' update to 0.1.8 adds 6 new resources.

The following operations need to be added. 
- [x] /family/:from
- [x] /shutup/:name/:from
- [x] /zayn/:from
- [x] /retard/:from
- [x] /thumbs/:from
- [x] /dosomething/:do/:something/:from
- [x] /bday/
- [x] /keepcalm/
- [x] mornin
- [x] /greed/
- [x] /bm/
- [x] /gfy/
- [x] /me/
- [x] /back/
- [x] /think/
- [x] /keep/
- [x] /single/
- [x] /look/
- [x] /single/
- [x] /look/
- [x] /looking/
- [x] /no/
- [x] /give/
- [x] /zero/
- [x] /pulp/
- [x] /sake/
- [x] /anyway/

**Comment by hydroid7** [comment]
It is enough to add some lines to the `Fuck` Enum?
BTW: It's a nice library, I'm using it for the android app :D

**Comment by SSederberg** [comment]
Thank you for the kind words! I plan to update this eventually™. I will add code as needed to make all the extensions work.
